name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    strategy:
      matrix:
        node-version: [12.18.3]

    steps:
      - uses: actions/checkout@v2

      - name: NodeJS Installation ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Dependencies Installation
        run: npm i
#
#      - name: build
#        run: npm run build
#
#      - name: install codecov
#        run: npm i -g codecov
#
#      - name: test
#        run: npm run cover
#
#      - name: report
#        run: npm run report
#
#      - name: codecov
#        run: codecov

  CD:
    runs-on: ubuntu-latest

    needs: CI

    steps:
      - uses: actions/checkout@v2

      - name: docker image build
        run: docker build .

      - name: upload to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: smj0385/jaksim
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
